server:
  port: 9091

spring:
  application:
    name: ch11-1-config-client
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    health:
      show-details: always
