server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    perferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
spring:
  application:
    name: eureka-server
    server:
      waitTimeInMsWhenSyncEmpty: 0
      enableSelfPreservation: false