server:
  port: 9092

spring:
  application:
    name: ch11-1-config-bus-client

  rabbitmq:
    host: localhost
    username: guest
    password: guest

  cloud:
    bus:
      trace:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    health:
      show-details: always
